// properties([
//     parameters([
//         // BUILD SOURCES ------------------------------------------------------
//         string(name: 'source_model', defaultValue: 'release/brewery-3.0',
//             description: 'Asset commitish to build'),
//         string(name: 'source_css', defaultValue: 'v11.3.0',
//             description: 'SDK commitish to build with'),
//         // BUILD OPTIONS ------------------------------------------------------
//         string(name: 'release_version', defaultValue: '3.0.0-dev.4',
//             description: 'Push named version as well as latest'),
//     ])
// ])

import org.jenkinsci.plugins.pipeline.modeldefinition.Utils

def pushToAcr(credentialsId) {
    withCredentials([
        usernamePassword(
            credentialsId: credentialsId,
            usernameVariable: 'ACR_USER',
            passwordVariable: 'ACR_PASS'
        )
    ]) {
        dir('src') {
            sh """
                export ACR_LOGIN_SERVER="\${ACR_USER}.azurecr.io"
                export IMAGE_NAME='cosmotech/brewerysamplesolution_simulator'
                export IMAGE_TAG='${params.release_version}'
                echo "Logging in to Azure Container Registry"
                echo \$ACR_PASS | docker login \$ACR_LOGIN_SERVER -u \$ACR_USER --password-stdin
                echo "Tagging image"
                docker tag \$IMAGE_NAME:\$IMAGE_TAG \$ACR_LOGIN_SERVER/\$IMAGE_NAME:\$IMAGE_TAG
                docker tag \$IMAGE_NAME:\$IMAGE_TAG \$ACR_LOGIN_SERVER/\$IMAGE_NAME:latest
                echo "Pushing image"
                docker push \$ACR_LOGIN_SERVER/\$IMAGE_NAME:\$IMAGE_TAG
                docker push \$ACR_LOGIN_SERVER/\$IMAGE_NAME:latest
            """
        }
    }
}

node('docker') {
  ansiColor('xterm') {
      stage('Git') {
        cleanWs()
        dir('src') {
            checkout([
                $class: 'GitSCM',
                branches: [[name: params.source_model]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [
                    [
                    $class: 'SubmoduleOption',
                    disableSubmodules: false,
                    parentCredentials: true,
                    recursiveSubmodules: true,
                    reference: '',
                    trackingSubmodules: false
                    ],
                    [$class: 'GitLFSPull']
                ],
                submoduleCfg: [],
                userRemoteConfigs: [[
                    url: 'git@github.com:Cosmo-Tech/brewery_sample_solution.git',
                    credentialsId: 'platform@cosmotech.com github'
                ]]
            ])
        }
        dir('CSS') {
            checkout([
                $class: 'GitSCM',
                branches: [[name: params.source_css]],
                userRemoteConfigs: [[url: 'ssh://git@cogit.cosmotech.com/prod/css.git', credentialsId: 'cogit']]
            ])
        }
        currentBuild.description = '[breweryCICD:' + params.source_model + ', CSS:' + params.source_css + ']'
      }
      def image = "$JOB_BASE_NAME".toLowerCase()
      stage('Prepare Env') {
        dir('src') {
            def userId = sh(script: 'id -u', returnStdout: true).trim()
            def dockerGid = sh(script: 'stat -c "%g" /var/run/docker.sock', returnStdout: true).trim()
            sh("docker build --pull -t $image --build-arg uid=$userId --build-arg docker_gid=$dockerGid cip")
        }
      }
      def job = env.JOB_BASE_NAME.toLowerCase().replace('%2f', '_')
      def container = "ci-$job-$BUILD_NUMBER".toLowerCase()
      docker.image("$image").inside("-u ciuser:docker \
                                     -v $HOME/.ccache:/home/ciuser/.ccache \
                                     -v $HOME/.cache:/home/ciuser/.cache \
                                     -v $HOME/.m2:/home/ciuser/.m2 \
                                     -v $HOME/.gradle:/home/ciuser/.gradle \
                                     -v $HOME/.embedpostgresql:/home/ciuser/.embedpostgresql \
                                     -v /var/run/docker.sock:/var/run/docker.sock \
                                     -v /usr/bin/docker:/usr/bin/docker \
                                     --name $container \
                                     -e CSMCLI_APP_UP_CONNECT=$container \
                                     -h $NODE_NAME \
                                     --ipc=host \
                                     --shm-size=256m") {
      stage('Build Studio') {
        sh 'python3 -m venv csmenv \
            && csmenv/bin/pip install CSS/csmcli'
        dir('CSS') {
          sh '../csmenv/bin/csm css --sources . sync --commit-ish no-sync'
          sh '../csmenv/bin/csm css --sources . configure --unity \
                                                          --no-studio \
                                                          --no-csmcli \
                                                          --minimum \
                                                          --minimum-extensions \
                                                          --build-type Release'
          sh '../csmenv/bin/csm css --sources . build'
        }
        stage('Build Model') {
          dir('src'){
            sh '../csmenv/bin/csm --css-home ../CSS/build build --flow'
          }
        }
        stage('Build docker image'){
          dir('src'){
            sh '../csmenv/bin/csm --css-home ../CSS/build docker build --flow'
            sh 'docker tag cosmotech/brewerysamplesolution_simulator:latest cosmotech/brewerysamplesolution_simulator:' + params.release_version
            sh 'docker image save cosmotech/brewerysamplesolution_simulator:latest -o Generated/Artifact/brewerysamplesolution_simulator.tar'
          }
        }
        stage('Run model tests') {
          dir('src'){
            sh '../csmenv/bin/csm --css-home ../CSS/build test --no-compress-output --output-junit testresults.xml'
          }
        }
      }
      stage('Push to Azure Container Registry for Warp') {
          pushToAcr('WARP_SPHINX_REGISTRY')
          pushToAcr('VELA_SPHINX_REGISTRY')
      }
      stage('Artifacts') {
          archiveArtifacts artifacts: 'src/Generated/Artifact/*', fingerprint: true
      }
      stage('Results') {
          xunit(
              tools: [
                CTest(pattern:
                  'src/Generated/Build/testresults.xml')
              ],
              thresholds: [failed(failureThreshold: '0')]
            )
      }
    }
  }
}
